language: java

jdk: openjdk11

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: build
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build -t linyang1218/puml:$TRAVIS_COMMIT .
        - docker push linyang1218/puml:$TRAVIS_COMMIT
    - stage: deploy
      if: branch = master
      script:
        - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh > /dev/null
        - heroku container:login
        - docker build --build-arg TAG=$TRAVIS_COMMIT -t registry.heroku.com/$APP/web -f Dockerfile.heroku .
        - docker push registry.heroku.com/$APP/web
        - heroku container:release web --app $APP

